// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWQNvJ-XgKUWJ7zMyQqg28NC2t5egtj4Y',
    appId: '1:249704016044:android:c49db42744283f59c01709',
    messagingSenderId: '249704016044',
    projectId: 't-store-e6dfa',
    storageBucket: 't-store-e6dfa.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC69_NfSLY9lpJzMv4x1uTEnQVvMebpZVI',
    appId: '1:249704016044:web:00b749e75dbae51dc01709',
    messagingSenderId: '249704016044',
    projectId: 't-store-e6dfa',
    authDomain: 't-store-e6dfa.firebaseapp.com',
    storageBucket: 't-store-e6dfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArhJr6vczZ1we42ZZGQcqYrdFkIh_TfV0',
    appId: '1:249704016044:ios:ad12d8b4b39ceb25c01709',
    messagingSenderId: '249704016044',
    projectId: 't-store-e6dfa',
    storageBucket: 't-store-e6dfa.firebasestorage.app',
    androidClientId: '249704016044-kgn0e4sd48e95u5s793e5m1rrgk5413d.apps.googleusercontent.com',
    iosClientId: '249704016044-et39pe6lmul58vn723oh51t4uu1u9soa.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
